### ISSUE TITLE
Error: spawnSync

### ISSUE THREAD

**Issue by tweetzal** [rubygarage/react-native-firebase-chat#4]
Followed install instructions, but throws : 

`Error: spawnSync /../../../../react-native-firebase-chat/node_modules/react-native/local-cli/setup_env.sh EACCES
    at _errnoException (util.js:1041:11)
    at spawnSync (child_process.js:569:20)
    at Object.execFileSync (child_process.js:606:13)
    at Object.run (/Applications/MAMP/htdocs/React_Native/react-native-firebase-chat/node_modules/react-native/local-cli/cliEntry.js:136:16)
    at Object.<anonymous> (/Users/tweetzal/npm-global/lib/node_modules/react-native-cli/index.js:117:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)`

Throws above error when I run ios? any ideas ?

I have xcode installed

**Comment by tweetzal** [comment]
resolved with chmod -R 777 node_modules
